### ISSUE TITLE
pip3 install --upgrade calysto-prolog throws FileNotFoundError

### ISSUE THREAD

**Issue by arne-cl** [Calysto/calysto_prolog#1]
Dear Doug,

when trying to install `calysto-prolog`(with and without `sudo`), this error occurred:

``` python
$ ~/podcasts $ pip3 install --upgrade calysto-prolog
Collecting calysto-prolog
  Using cached calysto_prolog-0.8.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-bbp5iw4d/calysto-prolog/setup.py", line 47, in <module>
        with open('README.md') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-bbp5iw4d/calysto-prolog

$ ~/podcasts $ pip3 --version
pip 7.1.2 from /usr/local/lib/python3.4/dist-packages (python 3.4)
```

Best regards,
Arne

**Comment by dsblank** [comment]
Thanks! Please try again... added a MANIFEST.in and new version in pypi

**Comment by arne-cl** [comment]
The installation itself doesn't throw any errors, but the `jupyter_console` module is missing.

``` python
$ ipython console --kernel calysto_prolog
Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/usr/local/lib/python3.4/dist-packages/IPython/__init__.py", line 118, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 591, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-111>", line 2, in initialize
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/IPython/terminal/ipapp.py", line 305, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/IPython/core/application.py", line 386, in initialize
    self.parse_command_line(argv)
  File "/usr/local/lib/python3.4/dist-packages/IPython/terminal/ipapp.py", line 300, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 487, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<decorator-gen-3>", line 2, in initialize_subcommand
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 418, in initialize_subcommand
    subapp = import_item(subapp)
  File "/usr/local/lib/python3.4/dist-packages/ipython_genutils/importstring.py", line 31, in import_item
    module = __import__(package, fromlist=[obj])
ImportError: No module named 'jupyter_console'

$ ipython --version
4.0.0
```

After installing `jupyter_console`, this happened:

``` python
$ ipython console --kernel calysto_prolog
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/jupyter_client/kernelspec.py", line 141, in get_kernel_spec
    resource_dir = d[kernel_name.lower()]
KeyError: 'calysto_prolog'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/usr/local/lib/python3.4/dist-packages/IPython/__init__.py", line 118, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 591, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-111>", line 2, in initialize
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/IPython/terminal/ipapp.py", line 305, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/IPython/core/application.py", line 386, in initialize
    self.parse_command_line(argv)
  File "/usr/local/lib/python3.4/dist-packages/IPython/terminal/ipapp.py", line 300, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 487, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<decorator-gen-3>", line 2, in initialize_subcommand
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 425, in initialize_subcommand
    self.subapp.initialize(argv)
  File "/usr/local/lib/python3.4/dist-packages/jupyter_console/app.py", line 144, in initialize
    super(ZMQTerminalIPythonApp, self).initialize(argv)
  File "<decorator-gen-111>", line 2, in initialize
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/IPython/terminal/ipapp.py", line 314, in initialize
    self.init_shell()
  File "/usr/local/lib/python3.4/dist-packages/jupyter_console/app.py", line 110, in init_shell
    JupyterConsoleApp.initialize(self)
  File "/usr/local/lib/python3.4/dist-packages/jupyter_client/consoleapp.py", line 329, in initialize
    self.init_kernel_manager()
  File "/usr/local/lib/python3.4/dist-packages/jupyter_client/consoleapp.py", line 283, in init_kernel_manager
    self.kernel_manager.start_kernel(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jupyter_client/manager.py", line 231, in start_kernel
    kernel_cmd = self.format_kernel_cmd(extra_arguments=extra_arguments)
  File "/usr/local/lib/python3.4/dist-packages/jupyter_client/manager.py", line 171, in format_kernel_cmd
    cmd = self.kernel_spec.argv + extra_arguments
  File "/usr/local/lib/python3.4/dist-packages/jupyter_client/manager.py", line 82, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "/usr/local/lib/python3.4/dist-packages/jupyter_client/kernelspec.py", line 143, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: 'calysto_prolog'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True
```

**Comment by dsblank** [comment]
Hmmm... not sure, but maybe you need to install the jupyter items first, then install prolog. Could you try installing calysto_prolog again, but with the "--upgrade" flag?

What are the contents of /usr/local/share/jupyter/kernels/ ?

What is the output of `jupyter-kernelspec list` ?

**Comment by arne-cl** [comment]
Packages seem okay, but the kernel isn't there.

``` python
$ python3 -m pip install --upgrade pip jupyter jupyter_console calysto_prolog
Requirement already up-to-date: pip in /usr/local/lib/python3.4/dist-packages
Requirement already up-to-date: jupyter in /usr/local/lib/python3.4/dist-packages
Requirement already up-to-date: jupyter-console in /usr/local/lib/python3.4/dist-packages
Requirement already up-to-date: calysto-prolog in /usr/local/lib/python3.4/dist-packages
Requirement already up-to-date: qtconsole in /usr/local/lib/python3.4/dist-packages (from jupyter)
Requirement already up-to-date: notebook in /usr/local/lib/python3.4/dist-packages (from jupyter)
Requirement already up-to-date: ipykernel in /usr/local/lib/python3.4/dist-packages (from jupyter)
Requirement already up-to-date: ipywidgets in /usr/local/lib/python3.4/dist-packages (from jupyter)
Requirement already up-to-date: nbconvert in /usr/local/lib/python3.4/dist-packages (from jupyter)
Requirement already up-to-date: ipython in /usr/local/lib/python3.4/dist-packages (from jupyter-console)
Requirement already up-to-date: jupyter-client in /usr/local/lib/python3.4/dist-packages (from jupyter-console)
Requirement already up-to-date: metakernel in /usr/local/lib/python3.4/dist-packages (from calysto-prolog)
Requirement already up-to-date: pygments in /usr/local/lib/python3.4/dist-packages (from qtconsole->jupyter)
Requirement already up-to-date: traitlets in /usr/local/lib/python3.4/dist-packages (from qtconsole->jupyter)
Requirement already up-to-date: jupyter-core in /usr/local/lib/python3.4/dist-packages (from qtconsole->jupyter)
Requirement already up-to-date: tornado>=4 in /usr/local/lib/python3.4/dist-packages (from notebook->jupyter)
Requirement already up-to-date: terminado>=0.3.3 in /usr/local/lib/python3.4/dist-packages (from notebook->jupyter)
Requirement already up-to-date: nbformat in /usr/local/lib/python3.4/dist-packages (from notebook->jupyter)
Requirement already up-to-date: ipython-genutils in /usr/local/lib/python3.4/dist-packages (from notebook->jupyter)
Requirement already up-to-date: jinja2 in /usr/local/lib/python3.4/dist-packages (from notebook->jupyter)
Requirement already up-to-date: mistune!=0.6 in /usr/local/lib/python3.4/dist-packages (from nbconvert->jupyter)
Requirement already up-to-date: pickleshare in /usr/local/lib/python3.4/dist-packages (from ipython->jupyter-console)
Requirement already up-to-date: decorator in /usr/local/lib/python3.4/dist-packages (from ipython->jupyter-console)
Requirement already up-to-date: simplegeneric>0.8 in /usr/local/lib/python3.4/dist-packages (from ipython->jupyter-console)
Requirement already up-to-date: pexpect in /usr/local/lib/python3.4/dist-packages (from ipython->jupyter-console)
Requirement already up-to-date: pyzmq>=13 in /usr/local/lib/python3.4/dist-packages (from jupyter-client->jupyter-console)
Requirement already up-to-date: ptyprocess in /usr/local/lib/python3.4/dist-packages (from terminado>=0.3.3->notebook->jupyter)
Requirement already up-to-date: jsonschema!=2.5.0,>=2.0 in /usr/local/lib/python3.4/dist-packages (from nbformat->notebook->jupyter)
Requirement already up-to-date: MarkupSafe in /usr/local/lib/python3.4/dist-packages (from jinja2->notebook->jupyter)
Requirement already up-to-date: path.py in /usr/local/lib/python3.4/dist-packages (from pickleshare->ipython->jupyter-console)
```

``` python
$ jupyter-kernelspec list
Available kernels:
  python3    /usr/local/lib/python3.4/dist-packages/ipykernel/resources

$ ls /usr/local/share/jupyter/kernels/                                                                                                               
ls: cannot access /usr/local/share/jupyter/kernels/: No such file or directory
```

**Comment by dsblank** [comment]
Should be fixed with latest update. Please see new README.md.
