### ISSUE TITLE
No module named Kernel error

### ISSUE THREAD

**Issue by jestinjoy** [Calysto/calysto_prolog#2]
I am trying to install prolog kernel with the command

`pip install calysto_prolog`

Last part of the error is

```

writing list of installed files to '/tmp/pip-MSM55J-record/install-record.txt'

/usr/local/lib/python2.7/dist-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.

  "You should import from ipykernel or jupyter_client instead.", ShimWarning)

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/pip-build-NErHtH/calysto-prolog/setup.py", line 64, in <module>

    'Programming Language :: Python :: 2',

  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup

    dist.run_commands()

  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/tmp/pip-build-NErHtH/calysto-prolog/setup.py", line 22, in run

    from metakernel.utils.kernel import install_kernel_resources

ImportError: No module named kernel
```

**Comment by dsblank** [comment]
Should be fixed with latest update. Please see new README.md.
