### ISSUE TITLE
Cant Install With Current Jupyter

### ISSUE THREAD

**Issue by techdragon** [Calysto/calysto_prolog#3]
```
    /Users/techdragon/.pyenv/versions/3.6.1/envs/jupyter/lib/python3.6/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated since IPython 4.0.You should import from ipykernel or jupyter_client instead.
      "You should import from ipykernel or jupyter_client instead.", ShimWarning)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/pg/hv1fbzjj0dlfkfjk116mz6nr0000gn/T/pip-build-k6_6ddjt/calysto-prolog/setup.py", line 64, in <module>
        'Programming Language :: Python :: 2',
      File "/Users/techdragon/.pyenv/versions/3.6.1/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Users/techdragon/.pyenv/versions/3.6.1/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/Users/techdragon/.pyenv/versions/3.6.1/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/private/var/folders/pg/hv1fbzjj0dlfkfjk116mz6nr0000gn/T/pip-build-k6_6ddjt/calysto-prolog/setup.py", line 22, in run
        from metakernel.utils.kernel import install_kernel_resources
    ModuleNotFoundError: No module named 'metakernel.utils.kernel'
```

**Comment by dsblank** [comment]
Acknowledged. Will try to revise this soon.

**Comment by dsblank** [comment]
Should be fixed with latest update. Please see new README.md.
